Issue/59 從首頁的餐廳列表可以連到某餐廳並進行訂位
astrocamp/14th-iDing pull request #94
Opened 2023-08-24 11:57 UTC by tysaiw

1. 使用的套件為 wicked
2. 可選日期不可早於今天(暫時，到時應該會以餐廳開放日期時間為主)
3. user 在 step 1 選擇完「日期、時間、人數」，並且會將資料儲存於 session
4. user 按下一頁會到 step 2 ，並且會顯示上頁所選的「日期、時間、人數」
5. user 可回上頁修改
6. 確認訂位後會顯示訂位資訊，並可於此頁進行「訂位取消」
7. 訂位完成（寫進 reservation ）會將 session 清空
8. user 會回到餐廳列表（預想他取消的話，也請訂其他餐廳！）
https://youtu.be/vcoyCsShLgw
https://youtu.be/eqtawEXRhm0

2023-08-24 12:46 UTC, cookiepingyen commented on app/models/reservation.rb
> +  validates :kid_num, presence: true, numericality: { greater_than: 0 }
小孩數量有一定要>0嗎?

2023-08-24 12:46 UTC, cookiepingyen commented on test/controllers/build_controller_test.rb
這個要刪掉嗎

2023-08-24 12:46 UTC, cookiepingyen commented on app/helpers/home_helper.rb
> +
多一行空白

2023-08-24 15:34 UTC, YorkYeh commented on .gitignore
> +.env
這個是不是每次都有啊?!

2023-08-24 15:36 UTC, YorkYeh commented on app/controllers/build_controller.rb
> +end
我想知道這裡在幹嘛~~

2023-08-24 16:01 UTC, Kkrystalll commented on .gitignore
> +.env
如果沒有用 env 可以移除喔

2023-08-24 16:01 UTC, Kkrystalll commented on app/controllers/admin/open_times_controller.rb
> +      Time.zone.parse(params[:open_time][:end_time])
這個是做什麼的？

2023-08-24 16:01 UTC, Kkrystalll commented on db/migrate/20230824062348_add_tel_to_reservation.rb
> +    add_column :reservations, :tel, :string
好像其他人也有新增到一樣的欄位

2023-08-24 16:01 UTC, Kkrystalll commented on app/views/home/index.html.erb
> +        <%= link_to '全部的餐廳', restaurants_path, class: 'mx-2 action-btn' %>
我隨便套樣式，跟打的「全部的餐廳」確定是你們網站要的嗎？
這個頁面樣式跟按鈕應該是什麼？
還是說因為這是功能不包含切版，所以才沒改？

2023-08-24 16:01 UTC, Kkrystalll commented on app/controllers/build_controller.rb
> +      )
create 裡面這串可以改做成私有方法放下面
```ruby
private
  def reservation_params
    params.permit(
      :name,
      :tel,
      :email,
      :gender,
      :purpose,
      :note
    ).merge(
      date: session[:first_step_data]['date'],
      time: session[:first_step_data]['time'],
      adult_num: session[:first_step_data]['adult_num'],
      kid_num: session[:first_step_data]['kid_num']
    )
  end
```
這邊就可以改成
```ruby
@reservation = @restaurant.reservations.create!(reservation_params)
```

2023-08-24 16:01 UTC, Kkrystalll commented on app/helpers/build_helper.rb
> +end
這檔案有需要嗎？

2023-08-24 16:01 UTC, Kkrystalll commented on app/models/reservation.rb
> +  validates :kid_num, presence: true, numericality: { greater_than: 0 }
可能要不能為負

2023-08-24 16:01 UTC, Kkrystalll commented on app/views/restaurants/index.html.erb
> +    <%# if r.date.to_date == Date.today %>
這句有要嗎？

2023-08-24 16:01 UTC, Kkrystalll commented
是不是沒跑 rubocop?

2023-08-25 03:01 UTC, tysaiw commented on app/controllers/admin/open_times_controller.rb
> +      Time.zone.parse(params[:open_time][:end_time])
這個好像是 rubocop 改的，我沒有動

2023-08-25 03:01 UTC, tysaiw commented on app/controllers/build_controller.rb
> +end
就是如果現在的step2(最後一步)
就導流到成功畫面

2023-08-25 03:01 UTC, tysaiw commented on app/helpers/build_helper.rb
> +end
抱歉沒有

2023-08-25 03:01 UTC, tysaiw commented on app/helpers/home_helper.rb
> +
這個好像是 rubocop....

2023-08-25 03:01 UTC, tysaiw commented on app/models/reservation.rb
> +  validates :kid_num, presence: true, numericality: { greater_than: 0 }
好 會改成 greater_than_or_equal_to: 0

2023-08-25 03:01 UTC, tysaiw commented on app/views/home/index.html.erb
> +        <%= link_to '全部的餐廳', restaurants_path, class: 'mx-2 action-btn' %>
因為想說是做功能，而且這個比較明白先讓大家知道這個是什麼意思（之前沒有討論到要做這個button）

2023-08-25 03:01 UTC, tysaiw commented on app/views/restaurants/index.html.erb
> +    <%# if r.date.to_date == Date.today %>
抱歉會刪掉

2023-08-25 06:43 UTC, tysaiw commented on .gitignore
> +.env
好

2023-08-25 06:43 UTC, tysaiw commented on app/controllers/build_controller.rb
> +      )
好

2023-08-25 06:43 UTC, tysaiw commented on test/controllers/build_controller_test.rb
要

2023-08-25 15:28 UTC, cookiepingyen approved these changes

2023-08-25 16:20 UTC, YorkYeh approved these changes

2023-08-25 17:23 UTC, Ju5tinDeng requested changes

2023-08-25 17:23 UTC, Ju5tinDeng commented on app/views/build/success_page.html.erb
> +    <p>大人數：<%= @reservation.adult_num %></p>
要不要加上 " 你已完成訂位 " 等字詞
名字後稱呼有需要加上嗎?
這裡只要秀大人的數量嗎?

2023-08-25 17:23 UTC, Ju5tinDeng commented on app/views/restaurants/index.html.erb
> +<h1>全部餐廳</h1>
選擇你想要用餐的餐廳 如何 ?

2023-08-25 17:23 UTC, Ju5tinDeng commented on app/views/home/index.html.erb
> +        <%= link_to '全部的餐廳', restaurants_path, class: 'mx-2 action-btn' %>
餐廳總覽 ?

2023-08-25 17:23 UTC, Ju5tinDeng commented on db/migrate/20230824062348_add_tel_to_reservation.rb
> +    add_column :reservations, :tel, :string
電話要不要加上 null: false

2023-08-25 17:26 UTC, Ju5tinDeng commented on app/views/home/index.html.erb
> +        <%= link_to '全部的餐廳', restaurants_path, class: 'mx-2 action-btn' %>
餐廳總覽 如何 ?

2023-08-26 03:42 UTC, tysaiw commented on app/views/restaurants/index.html.erb
> +<h1>全部餐廳</h1>
可以呀 這頁應該是要吃列表那頁的 view（York那邊有切我記得）
這邊只是要讓這個功能可以順路

2023-08-26 03:42 UTC, tysaiw commented on app/views/build/success_page.html.erb
> +    <p>大人數：<%= @reservation.adult_num %></p>
嗯嗯這頁會再調整
下一張票就是會把畫面都再修調
目前主要是把功能順過
例如也會用個按鈕連回首頁之類（沒取消的話）

2023-08-26 03:42 UTC, tysaiw commented on app/views/home/index.html.erb
> +        <%= link_to '全部的餐廳', restaurants_path, class: 'mx-2 action-btn' %>
我會傾向「合作餐廳」
因為iDing主要面向的是餐廳owner
訂位的連結雖然從這邊可以訂
但主要應該會是餐廳owner在自己官網、社群露出的連結訂位

2023-08-26 03:42 UTC, tysaiw commented on db/migrate/20230824062348_add_tel_to_reservation.rb
> +    add_column :reservations, :tel, :string
ok

2023-08-26 03:57 UTC, Ju5tinDeng approved these changes

2023-08-26 03:57 UTC, merged